services:
  immich-discord-selfbot:
    build: .
    environment:
      - BASE_URL=${BASE_URL}
      - API_KEY=${API_KEY}
      - ADMIN_API_KEY=${ADMIN_API_KEY}
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - MAX_FILE_SIZE_MB=${MAX_FILE_SIZE_MB}
      - BOT_PREFIX=${BOT_PREFIX}
    volumes:
      - ./main.py:/app/main.py
      - ./cogs:/app/cogs
    restart: unless-stopped